spring:
  # 数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/tiktok?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: videoservice
  mvc:
    static-path-pattern:server: /**
  # 最大文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    host: 106.75.247.170
    port: 5672
    username: root
    password: 123456
    virtual-host: / # 虚拟主机
    listener:
      direct:
        prefetch: 1 # 每个消费者每次只消费一条消息，不会出现高消费的情况，也就是承担不了那么多消息
  cloud:
    # nacos相关地址
    nacos:
      server-addr: 106.75.247.170:8848
  redis:
    host: localhost
    port: 6379
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 600000
    pool:
      max-active: 8 # 连接池最大连接数
      max-wait: -1 # 最大阻塞等待时间没有限制
      min-idle: 0 # 连接池中最小空闲连接数
      timeout: 200 # 连接超时时间
server:
  port: 9190

# 缓存过期值随机打散(30分钟到60分钟)
random_start: 30
random_end: 30
# 腾讯云上传文件的配置
tencent:
  cos:
    secretId: AKID496vaHqKgv21PcgdP0ty7LVeqDd5YvGa
    secretKey: VvJjAc4RmBf7Z7kJrP0gT5hATaAezBGH
    bucketName: zzzi-img-1313100942
    region: ap-beijing
# 视频和封面的本地保存地址
video_save_path: "G:/Java/tiktok/resource/static/video/"
cover_save_path: "G:/Java/tiktok/resource/static/cover/"
# 推荐视频缓存的最大数量，防止出现大key
video_feed_max_size: 5000
# 用户作品缓存的最大数量，防止出现大key
user_works_max_size: 1000
# 视频评论缓存的最大数量，防止大key
video_comment_max_size: 5000
# 每次推荐视频的数量
feed_size: 30

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 日志输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    # 这个包下的日志记录级别为debug
    com.zzzi: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
# 防止远程调用超时
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
ribbon.nacos.enabled: true
#ribbon:
#  ConnectTimeout: 5000
#  ReadTimeout: 5000
#  eager-load:
#    enabled: true # 开启饥饿加载
#    clients: # 指定饥饿加载的服务名称
#      - userservice
## 负载均衡规则
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
