---
--- Generated by Luanalysis
--- Created by zzzi.
--- DateTime: 2024/4/12 22:12
---
local key = KEYS[1]; -- 锁的key
local threadId = ARGV[1]; --线程唯一id
local releaseTime = ARGV[2] --锁的过期时间

-- 判断锁是否存在
if (redis.call('exists', key) == 0) then
    -- 不存在直接加锁
    redis.call('hset', key, threadId, '1');
    -- 设置锁的有效期
    redis.call('expire', key, releaseTime);
    return 1;
end ;

--锁已经存在，判断是不是自己加的锁，实现可重入
if (redis.call('hexists', key, threadId) == 1) then
    -- 到这里说明是自己加的锁，重入次数+1
    redis.call('hincrby', key, threadId, '1');
    --重新设置锁的有效期
    redis.call('expire', key, releaseTime);
    return 1;
end ;
-- 加锁失败返回0
return 0;