---
--- Generated by Luanalysis
--- Created by zzzi.
--- DateTime: 2024/4/12 22:08
---
local key = KEYS[1]; -- 锁的key
local threadId = ARGV[1]; --线程唯一id
local releaseTime = ARGV[2] --锁的过期时间

--判断当前锁是不是自己加的
if (redis.call('hexists', key, threadId) == 0) then
    return 0;
end ;

--到这里说明是自己的锁,重入次数-1
local count = redis.call('hincrby', key, threadId, -1);

--重入次数为0才删除锁
if (count > 0) then
    -- 重入次数不为0，更新锁的有效时间
    redis.call('expire', key, releaseTime);
    return 1;
else
    -- 重入次数为0删除锁
    redis.call('del', key);
    return 1;
end ;

